name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Create appsettings.json
        run: echo '${{ secrets.APP_SETTINGS_CONTENT }}' > jjodel-persistence/jjodel-persistence/appsettings.json

      - name: Build with dotnet
        run: dotnet build jjodel-persistence/jjodel-persistence.sln --configuration Release     

      - name: dotnet publish
        run: dotnet publish jjodel-persistence/jjodel-persistence.sln -c Release -o ./publish

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./publish
          file: ./jjodel-persistence/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/jjodel-persistence:latest
